name: flutter_admin
description: Flutter application admin panel
version: 0.1.0-dev.1
homepage: https://github.com/Frezyx/flutter_admin

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  talker_flutter: ^4.0.0
  talker_dio_logger: ^4.0.0
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  path_provider: ^2.1.2
  group_button: ^5.3.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
