name: debug_friend

on:
  push:
    paths:
      - "packages/debug_friend/lib/**"
      - "packages/debug_friend/test/**"
      - ".github/workflows/debug_friend.yaml"

  pull_request:
    paths:
      - "packages/debug_friend/lib/**"
      - "packages/debug_friend/test/**"
      - ".github/workflows/debug_friend.yaml"

jobs:
  test:
    defaults:
      run:
        working-directory: packages/debug_friend
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "12.x"
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings .
