name: debug_friend

on:
  push:
    paths:
      - "packages/debug_friend/**"
      - ".github/workflows/debug_friend.yaml"

  pull_request:
    paths:
      - "packages/debug_friend/**"
      - ".github/workflows/debug_friend.yaml"

jobs:
  test:
    defaults:
      run:
        working-directory: packages/talker
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze
